apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-flask-app
  namespace: {{ .Values.namespace }}
  labels:
    app: demo-flask-app
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: demo-flask-app
  template:
    metadata:
      labels:
        app: demo-flask-app
    spec:
      containers:
      - name: flask-app
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 30
          periodSeconds: 10