apiVersion: v1
kind: Service
metadata:
  name: demo-flask-app-service
  namespace: { { .Values.namespace | default "default" } }
  labels:
    app: demo-flask-app
spec:
  type: ClusterIP
  ports:
    - port: { { .Values.service.port } }
      targetPort: { { .Values.service.targetPort } }
      protocol: TCP
  selector:
    app: demo-flask-app
