name: Build, Tag, Push Docker Image and Update Helm

on:
  push:
    paths:
      - "flask_app/**"
      - ".github/workflows/ci.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image with Git SHA tag
        uses: docker/build-push-action@v5
        with:
          context: ./flask_app
          push: true
          tags: |
            dhruvre/flask-app:latest
            dhruvre/flask-app:${{ github.sha }}

      - name: Sync ArgoCD app
        env:
          ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
        run: |
          curl -X POST https://506196ef442c.ngrok-free.app/api/v1/applications/demo-flask-app/sync \
            -H "Authorization: Bearer ${ARGOCD_AUTH_TOKEN}"

      - name: Update Helm values with new image tag
        run: |
          sed -i.bak "s|tag: .*|tag: ${{ github.sha }}|" demo/values.yaml

      - name: Commit updated values.yaml
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          echo "PAT length: ${#GH_PAT}"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git
          git add demo/values.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push origin HEAD:master
